### ISSUE TITLE
Not working with Image mask with transparent pixels

### ISSUE THREAD

**Issue by Gilianp** [blaugold/widget_mask#2]
I'm trying to create a mask using an image which has a transparency (where it should be hidden). The result is that it's black where the pixels are transparent

image:
![image](https://user-images.githubusercontent.com/5700016/187030025-8a490f19-c379-4362-a68e-67d39bbe82a9.png)

mask: (white with transparent)
![bg_baixaria_forma_inner_redonda_1_2_mask](https://user-images.githubusercontent.com/5700016/187030036-0c4e0b7b-4553-496d-82e9-54a35a70b4e5.png)

result:
![res](https://user-images.githubusercontent.com/5700016/187030122-49f53ad2-2310-4f7a-89a1-c2df69e04bcf.png)

I want that black parts become transparent (behind have the rest of the application)

code:
   WidgetMask(
     blendMode: BlendMode.dstATop,    
     mask: Image.asset(
       "path_mask",
     ),
     child: Image.asset(
       "path_image",
     ),
   )

**Comment by blaugold** [comment]
I think with a mask like that, you want to use `BlendMode.multiply`.

**Comment by Gilianp** [comment]
> I think with a mask like that, you want to use `BlendMode.multiply`.

I tested all BlendMode options and the modes that should erase the target where there are transparent pixels in the mask image, turn black. It seems that it is not possible to use an image with transparent pixels as a mask in flutter. On android this is very easy, these blendmodes work with them. I found another solution using ImageShader but there it is not allowed to use centerSlice in the mask image (here: https://stackoverflow.com/a/60505529/2097909)

**Comment by blaugold** [comment]
Hm, did you try enabling [`childSaveLayer`](https://pub.dev/documentation/widget_mask/latest/widget_mask/WidgetMask/childSaveLayer.html)?

**Comment by Gilianp** [comment]
> Hm, did you try enabling [`childSaveLayer`](https://pub.dev/documentation/widget_mask/latest/widget_mask/WidgetMask/childSaveLayer.html)?

Wow, now its working! (with BlendMode.dstATop that is correct for this case). Thanks for you support!
