### ISSUE TITLE
WidgetMask is not working flutter web using HTML version.

### ISSUE THREAD

**Issue by shofizone** [blaugold/widget_mask#3]
WidgetMask is not working on the flutter web HTML version. While it is working on the canvas kit version.

step to reproduce: 
run the example project with this command.
`flutter run -d chrome --web-renderer html --release` <- Not working

Expected to run this example project as it runs on another platform, (eg. android/OSX/flutter web canvas kit). rather than showing the mask widget it is showing a stack view.
`flutter build web --web-renderer canvaskit --release` <- working

**Comment by blaugold** [comment]
Unfortunately, the HTML renderer uses multiple DOM Canvas elements, which cannot be blended in the way that would be necessary for this library to work.

I would suggest only using the canvaskit renderer, or if that is not an option, detect which rendered is being used at runtime and switch to an alternative representation that does not use `WidgetMask` when the html renderer is active.
